// svelte/src/routes/+page.svelte
<script lang="ts">
  interface Link {
    href: string;
    label: string;
  }
  const links: Link[] = [
    { href: '/1-state', label: '$state' },
  ]
</script>

<ol class="list-decimal pl-6 space-y-2 text-lg">
  {#each links as link, index (index)}
    <li>
      <a href={link.href} class="text-blue-600 underline">{link.label}</a>
    </li>
  {/each}
</ol>

// react/src/routes/index.tsx
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/')({
  component: App,
})

function App() {
  return (
    <>
      <h1>Index</h1>
      <ul className="list-disc pl-5">
        <li><a href="/1-jsx" className="underline text-blue-600">1-jsx</a></li>
      </ul>
    </>
  )
}
